"""add puzzle id to comments table

Revision ID: 69bea51a93b0
Revises: bafee2bceeae
Create Date: 2024-05-03 09:14:29.771399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69bea51a93b0'
down_revision = 'bafee2bceeae'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puzzle_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_comment_puzzle_id_wordle_puzzle'), 'wordle_puzzle', ['puzzle_id'], ['puzzle_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('puzzle_id')

    # ### end Alembic commands ###