"""Add is_active column to user table

Revision ID: 81dd34cb2df6
Revises: f1a0b60f6cb8
Create Date: 2024-05-17 23:59:19.583599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81dd34cb2df6'
down_revision = 'f1a0b60f6cb8'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_puzzle_id_wordle_puzzle', type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_puzzle_id_wordle_puzzle', 'wordle_puzzle', ['puzzle_id'], ['puzzle_id'])

    with op.batch_alter_table('score_table', schema=None) as batch_op:
        batch_op.alter_column('number_of_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('wordle_puzzle', schema=None) as batch_op:
        batch_op.alter_column('times_puzzle_played',
               existing_type=sa.INTEGER(),
               nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordle_puzzle', schema=None) as batch_op:
        batch_op.alter_column('times_puzzle_played',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('score_table', schema=None) as batch_op:
        batch_op.alter_column('number_of_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_puzzle_id_wordle_puzzle', 'wordle_puzzle', ['puzzle_id'], ['puzzle_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
