"""remove unecessary table and add default value

Revision ID: dfa35be53916
Revises: 81dd34cb2df6
Create Date: 2024-05-19 13:06:59.677188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa35be53916'
down_revision = '81dd34cb2df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('comment_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('comment_text', sa.VARCHAR(length=256), nullable=True),
    sa.Column('posted_date', sa.DATETIME(), nullable=True),
    sa.Column('puzzle_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['wordle_puzzle.puzzle_id'], name='fk_comment_puzzle_id_wordle_puzzle'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###
