"""add suggested column

Revision ID: f1a0b60f6cb8
Revises: 69bea51a93b0
Create Date: 2024-05-03 15:49:20.511980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a0b60f6cb8'
down_revision = '69bea51a93b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordle_puzzle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('times_puzzle_played', sa.Integer(), nullable=False))
    with op.batch_alter_table('score_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordle_puzzle', schema=None) as batch_op:
        batch_op.drop_column('times_puzzle_played')
    with op.batch_alter_table('score_table', schema=None) as batch_op:
        batch_op.drop_column('number_of_attempts')
    # ### end Alembic commands ###
